### PR TITLE
Fix the second parameter of Split

### PR DESCRIPTION
**Pull request by ailispaw**
to get fields correctly.

### CODE REVIEW

**Comment by ailispaw** [comment]
It seems my misunderstanding... Sorry.

**Comment by ailispaw** [comment]
But I cannot understand why it couldn't get id from fields correctly...

**Comment by astj** [comment]
@ailispaw Hi. Can you explain your problem in detail? (like your `docker ps` output with your private labels/names masked)

**Comment by ailispaw** [comment]
I tried to reproduce it, but I couldn't.
It may depend on my environment at that time when I restarted mackerel-agent container very often.
Never mind.

**Pull request closed without merging**
