### PR TITLE
[memcached] Support -metric-key-prefix option 

### PR DESCRIPTION
**Pull request by astj**
There're some plugins already supporting this option(mysql, redis, ...).

### CODE REVIEW

**Comment by Songmu** [comment]
You can implement `PluginWithPrefix` interface on this situation.

**Comment by astj** [comment]
@Songmu Thanks. Changed implementation with `PluginWithPrefix` interface.

**Comment by Songmu** [comment]
LGTM!

**Comment by astj** [comment]
Thanks!!

**Pull request merged**
