### PR TITLE
Add mackerel-plugin-unicorn

### PR DESCRIPTION
**Pull request by linyows**
A mackerel plugin for [Unicorn](https://github.com/defunkt/unicorn).

### CODE REVIEW

**Comment by Songmu** [comment]
Thank you! I'll review later.

**Comment by Songmu** [comment]
@linyows Sorry for slow response.

I propose one point.

Could you change metric name into `busy_wokers` and `idle_workers`, and stacked them like mackerel-plugins-apache2 and mackerl-plugins-plack?

If you have hard reason to change them, it is ok to stay them.

**Comment by linyows** [comment]
@Songmu Well, that's a good suggestion.

**Comment by Songmu** [comment]
Thank you!

**Pull request merged**
