### PR TITLE
Implement mackerel-plugin-twemproxy

### PR DESCRIPTION
**Pull request by yoheimuta**
We plan to use this plugin in production. After our test trial in production, we are sure that it's helpful for operators monitoring twemproxy(s). 

In my opinion, twemproxy is [a somewhat defacto standard](https://github.com/twitter/twemproxy#companies-using-twemproxy-in-production) proxy for redis and memcached, so I'm posting this PR.

- [x] Review https://github.com/mackerelio/mackerel-agent-plugins/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by yoheimuta** [comment]
ping. (because it passed 13 days)

**Comment by stefafafan** [comment]
Thanks for the pull-request and sorry for the late reply.
We will take a look at it in a moment so please wait a bit. 🙇

**Comment by yoheimuta** [comment]
Thanks for the reply 😌

**Comment by stefafafan** [comment]
I took a look at the code and noticed you decided to skip `fragments` and `server_ejected_at` . Is there a reason you made that decision?

**Comment by yoheimuta** [comment]
@stefafafan 

> I took a look at the code and noticed you decided to skip fragments and server_ejected_at

Yes, I skip fragments and server_ejected_at.

>> fragments           "# fragments created from a multi-vector request"
>> https://github.com/twitter/twemproxy#observability

>> timestamp when server was ejected in usec since epoch
>> https://github.com/twitter/twemproxy/blob/0f9e1baf06db478065ba43402b975c57a567d00f/src/nc_stats.h#L40

> Is there a reason you made that decision?

Yes. 

>> fragments

`We` don't mind any number of fragments created, because we think fragments is relatively not important for understanding the twemproxy loads in our usage.

>> server_ejected_at

I couldn't image the graph to point those timestamp data（= タイムスタンプ値をグラフで表現するわかりやすい方法が思い浮かばなかったので、今回の実装から除外しました）.

Summarizing the above, I decided to skip these parameters because other users should just implement to add these when users needed appear.
( I should write this note in pr description 🙇 )

**Comment by stefafafan** [comment]
@yoheimuta 
Thanks for the description.

> I decided to skip these parameters because other users should just implement to add these when users needed appear

I see, that makes sense. Perhaps write a note about fragments and server_ejected_at in the README.md might be great if you don't mind.

Other than that, great work!

**Comment by yoheimuta** [comment]
@stefafafan Thanks for the review.

I wrote a note in the README.md 11beca9.

**Comment by stefafafan** [comment]
@yoheimuta 
Sorry to make you wait, thanks for adding to the readme!

**Comment by yoheimuta** [comment]
Thanks!

**Pull request merged**
