### PR TITLE
[aws-dynamodb] add TimeToLiveDeletedItemCount metrics

### PR DESCRIPTION
**Pull request by astj**
Recently added to CloudWatch, and I missed to incude this metrics.

### CODE REVIEW

**Comment by stefafafan** [comment]
Ah, I see.
`ReturnedBytes` and `ReturnedRecordsCount` seem to be missing as well, is this fine?

**Comment by astj** [comment]
> `ReturnedBytes` and `ReturnedRecordsCount` seem to be missing as well, is this fine?

Those are for DynamoDB Streams, so I didn't include it. (As I documented at https://github.com/mackerelio/mackerel-agent-plugins/commit/af80a32dbde86ad7406bb60b09353e62d6b2dc5d)

**Comment by itchyny** [comment]
LGTM

**Comment by astj** [comment]
Thanks!

**Pull request merged**
