### PR TITLE
[jvm] fix jinfo command timed out error is not logged

### PR DESCRIPTION
**Pull request by susisu**

### CODE REVIEW

**Comment by astj** [comment]
We should also remove other `os.Exit` s during FetchMetrics?  Just returning error and handling the error in FetchMetrics seems more healthy..

**Comment by astj** [comment]
This change itself seems good, as long as CI passes

**Comment by susisu** [comment]
> We should also remove other os.Exit s during FetchMetrics? Just returning error and handling the error in FetchMetrics seems more healthy..

Ah, yes. I changed so f5d644f.

**Comment by susisu** [comment]
Thank you for the review!

**Pull request merged**
