### PR TITLE
[inode] Add support for df mutiline output

### PR DESCRIPTION
**Pull request by etsxxx**
`df -i` command outputs multi lines when dev path was long.

```
$ df -i
Filesystem            Inodes   IUsed   IFree IUse% Mounted on
/dev/mapper/VolGroup00-lv_root
                     2542736  244177 2298559   10% /
```

I added support for such output to inode plugin.

### CODE REVIEW

**Comment by Songmu** [comment]
How about using `df -iP` on linux environment?

**Comment by etsxxx** [comment]
Don't treat Mac OS, `df -iP` is best.

**Comment by Songmu** [comment]
How about #185 ?

**Comment by etsxxx** [comment]
Okey, We can get same metrics.

**Comment by Songmu** [comment]
I adopt #185, so I'm sorry to close this issue.

**Pull request closed without merging**
